"""Regenerate version_info.txt from UBIC_VERSION in ubic_tracker.py.

The Windows VERSIONINFO resource repeats the version in five places, so hand
editing it for every release invites the numbers drifting apart from the one the
app reports. UBIC_VERSION is the single source of truth; this rewrites the
resource file to match.

build.bat runs this automatically. To do it by hand:

    python make_version_info.py
"""
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
SOURCE = os.path.join(HERE, "ubic_tracker.py")
TARGET = os.path.join(HERE, "version_info.txt")

TEMPLATE = '''# GENERATED by make_version_info.py - do not edit.
# Change UBIC_VERSION in ubic_tracker.py and rebuild instead.
#
# Windows VERSIONINFO resource, embedded by PyInstaller via --version-file.
# Without it, Task Manager, Startup Apps and Properties -> Details fall back to
# the raw filename and show "Ubic.exe". FileDescription is the field they read.

VSVersionInfo(
  ffi=FixedFileInfo(
    filevers=({v0}, {v1}, {v2}, 0),
    prodvers=({v0}, {v1}, {v2}, 0),
    mask=0x3f,
    flags=0x0,
    OS=0x40004,      # VOS_NT_WINDOWS32
    fileType=0x1,    # VFT_APP
    subtype=0x0,
    date=(0, 0)
  ),
  kids=[
    StringFileInfo([
      # 0409 = US English, 04B0 = Unicode. Must match the Translation below.
      StringTable(
        '040904B0',
        [StringStruct('CompanyName', 'Ubic'),
         StringStruct('FileDescription', 'Ubic'),
         StringStruct('FileVersion', '{version}.0'),
         StringStruct('InternalName', 'Ubic'),
         StringStruct('LegalCopyright', ''),
         StringStruct('OriginalFilename', 'Ubic.exe'),
         StringStruct('ProductName', 'Ubic'),
         StringStruct('ProductVersion', '{version}.0')])
    ]),
    VarFileInfo([VarStruct('Translation', [1033, 1200])])
  ]
)
'''


def read_version():
    """Pull UBIC_VERSION out of the source without importing it.

    Importing ubic_tracker would pull in winreg, pystray and a Tk root window,
    none of which belong in a build step.
    """
    with open(SOURCE, encoding="utf-8") as f:
        match = re.search(r'^UBIC_VERSION\s*=\s*["\']([^"\']+)["\']', f.read(), re.M)
    if not match:
        raise SystemExit(f"Could not find UBIC_VERSION in {SOURCE}")

    version = match.group(1)
    if not re.fullmatch(r"\d+\.\d+\.\d+", version):
        raise SystemExit(
            f"UBIC_VERSION is {version!r}; expected three numbers like 1.2.3. "
            f"Windows needs numeric version fields."
        )
    return version


def main():
    version = read_version()
    major, minor, patch = version.split(".")
    content = TEMPLATE.format(version=version, v0=major, v1=minor, v2=patch)

    with open(TARGET, "w", encoding="utf-8") as f:
        f.write(content)

    print(f"version_info.txt written for Ubic {version}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
    
